development:
 adapter: postgresql
 encoding: unicode
 database: web_albums_developement
 pool: 5
 username: enbake
 password: enbake
 host: localhost

test:
 adapter: postgresql
 encoding: unicode
 database: web_albums_test
 pool: 5
 username: enbake
 password: enbake
 host: localhost

production:
 adapter: postgresql
 encoding: unicode
 database: web_albums_production
 pool: 5
 username: enbake
 password: enbake
 host: localhost